# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: dhruva/v1/auth.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'dhruva/v1/auth.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x64hruva/v1/auth.proto\x12\tdhruva.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"g\n\x04User\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x14\n\x0c\x64isplay_name\x18\x03 \x01(\t\x12.\n\ncreated_at\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"/\n\x0cLoginRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"`\n\tTokenPair\x12\x14\n\x0c\x61\x63\x63\x65ss_token\x18\x01 \x01(\t\x12\x15\n\rrefresh_token\x18\x02 \x01(\t\x12\x12\n\nexpires_in\x18\x03 \x01(\x05\x12\x12\n\ntoken_type\x18\x04 \x01(\t\"\'\n\x0eRefreshRequest\x12\x15\n\rrefresh_token\x18\x01 \x01(\t\"\x0f\n\rLogoutRequest\"\x07\n\x05\x45mpty\"\x0b\n\tMeRequest2\xe4\x01\n\x0b\x41uthService\x12\x36\n\x05Login\x12\x17.dhruva.v1.LoginRequest\x1a\x14.dhruva.v1.TokenPair\x12:\n\x07Refresh\x12\x19.dhruva.v1.RefreshRequest\x1a\x14.dhruva.v1.TokenPair\x12\x34\n\x06Logout\x12\x18.dhruva.v1.LogoutRequest\x1a\x10.dhruva.v1.Empty\x12+\n\x02Me\x12\x14.dhruva.v1.MeRequest\x1a\x0f.dhruva.v1.Userb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dhruva.v1.auth_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USER']._serialized_start=68
  _globals['_USER']._serialized_end=171
  _globals['_LOGINREQUEST']._serialized_start=173
  _globals['_LOGINREQUEST']._serialized_end=220
  _globals['_TOKENPAIR']._serialized_start=222
  _globals['_TOKENPAIR']._serialized_end=318
  _globals['_REFRESHREQUEST']._serialized_start=320
  _globals['_REFRESHREQUEST']._serialized_end=359
  _globals['_LOGOUTREQUEST']._serialized_start=361
  _globals['_LOGOUTREQUEST']._serialized_end=376
  _globals['_EMPTY']._serialized_start=378
  _globals['_EMPTY']._serialized_end=385
  _globals['_MEREQUEST']._serialized_start=387
  _globals['_MEREQUEST']._serialized_end=398
  _globals['_AUTHSERVICE']._serialized_start=401
  _globals['_AUTHSERVICE']._serialized_end=629
# @@protoc_insertion_point(module_scope)
