# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: dhruva/v1/common.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'dhruva/v1/common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x64hruva/v1/common.proto\x12\tdhruva.v1\x1a\x1fgoogle/protobuf/timestamp.proto\")\n\x05Money\x12\x0e\n\x06\x61mount\x18\x01 \x01(\t\x12\x10\n\x08\x63urrency\x18\x02 \x01(\t\"%\n\x04Page\x12\x0e\n\x06offset\x18\x01 \x01(\x05\x12\r\n\x05limit\x18\x02 \x01(\x05\"8\n\x08PageInfo\x12\r\n\x05total\x18\x01 \x01(\x05\x12\x0e\n\x06offset\x18\x02 \x01(\x05\x12\r\n\x05limit\x18\x03 \x01(\x05\"k\n\tAuditMeta\x12.\n\ncreated_at\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12.\n\nupdated_at\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp*/\n\x04Side\x12\x14\n\x10SIDE_UNSPECIFIED\x10\x00\x12\x07\n\x03\x42UY\x10\x01\x12\x08\n\x04SELL\x10\x02*P\n\tOrderType\x12\x1a\n\x16ORDER_TYPE_UNSPECIFIED\x10\x00\x12\n\n\x06MARKET\x10\x01\x12\t\n\x05LIMIT\x10\x02\x12\x06\n\x02SL\x10\x03\x12\x08\n\x04SL_M\x10\x04*x\n\x0bOrderStatus\x12\x1c\n\x18ORDER_STATUS_UNSPECIFIED\x10\x00\x12\x0b\n\x07PENDING\x10\x01\x12\x08\n\x04OPEN\x10\x02\x12\n\n\x06\x46ILLED\x10\x03\x12\x0b\n\x07PARTIAL\x10\x04\x12\x0c\n\x08REJECTED\x10\x05\x12\r\n\tCANCELLED\x10\x06*Q\n\x08\x45xchange\x12\x18\n\x14\x45XCHANGE_UNSPECIFIED\x10\x00\x12\x07\n\x03NSE\x10\x01\x12\x07\n\x03\x42SE\x10\x02\x12\x07\n\x03NFO\x10\x03\x12\x07\n\x03\x42\x46O\x10\x04\x12\x07\n\x03MCX\x10\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dhruva.v1.common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SIDE']._serialized_start=319
  _globals['_SIDE']._serialized_end=366
  _globals['_ORDERTYPE']._serialized_start=368
  _globals['_ORDERTYPE']._serialized_end=448
  _globals['_ORDERSTATUS']._serialized_start=450
  _globals['_ORDERSTATUS']._serialized_end=570
  _globals['_EXCHANGE']._serialized_start=572
  _globals['_EXCHANGE']._serialized_end=653
  _globals['_MONEY']._serialized_start=70
  _globals['_MONEY']._serialized_end=111
  _globals['_PAGE']._serialized_start=113
  _globals['_PAGE']._serialized_end=150
  _globals['_PAGEINFO']._serialized_start=152
  _globals['_PAGEINFO']._serialized_end=208
  _globals['_AUDITMETA']._serialized_start=210
  _globals['_AUDITMETA']._serialized_end=317
# @@protoc_insertion_point(module_scope)
