# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from dhruva.v1 import orders_pb2 as dhruva_dot_v1_dot_orders__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in dhruva/v1/orders_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class OrderServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PlaceOrder = channel.unary_unary(
                '/dhruva.v1.OrderService/PlaceOrder',
                request_serializer=dhruva_dot_v1_dot_orders__pb2.PlaceOrderRequest.SerializeToString,
                response_deserializer=dhruva_dot_v1_dot_orders__pb2.Order.FromString,
                _registered_method=True)
        self.CancelOrder = channel.unary_unary(
                '/dhruva.v1.OrderService/CancelOrder',
                request_serializer=dhruva_dot_v1_dot_orders__pb2.CancelOrderRequest.SerializeToString,
                response_deserializer=dhruva_dot_v1_dot_orders__pb2.Order.FromString,
                _registered_method=True)
        self.ModifyOrder = channel.unary_unary(
                '/dhruva.v1.OrderService/ModifyOrder',
                request_serializer=dhruva_dot_v1_dot_orders__pb2.ModifyOrderRequest.SerializeToString,
                response_deserializer=dhruva_dot_v1_dot_orders__pb2.Order.FromString,
                _registered_method=True)
        self.ListOrders = channel.unary_unary(
                '/dhruva.v1.OrderService/ListOrders',
                request_serializer=dhruva_dot_v1_dot_orders__pb2.ListOrdersRequest.SerializeToString,
                response_deserializer=dhruva_dot_v1_dot_orders__pb2.ListOrdersResponse.FromString,
                _registered_method=True)


class OrderServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def PlaceOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ModifyOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListOrders(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OrderServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PlaceOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.PlaceOrder,
                    request_deserializer=dhruva_dot_v1_dot_orders__pb2.PlaceOrderRequest.FromString,
                    response_serializer=dhruva_dot_v1_dot_orders__pb2.Order.SerializeToString,
            ),
            'CancelOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelOrder,
                    request_deserializer=dhruva_dot_v1_dot_orders__pb2.CancelOrderRequest.FromString,
                    response_serializer=dhruva_dot_v1_dot_orders__pb2.Order.SerializeToString,
            ),
            'ModifyOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.ModifyOrder,
                    request_deserializer=dhruva_dot_v1_dot_orders__pb2.ModifyOrderRequest.FromString,
                    response_serializer=dhruva_dot_v1_dot_orders__pb2.Order.SerializeToString,
            ),
            'ListOrders': grpc.unary_unary_rpc_method_handler(
                    servicer.ListOrders,
                    request_deserializer=dhruva_dot_v1_dot_orders__pb2.ListOrdersRequest.FromString,
                    response_serializer=dhruva_dot_v1_dot_orders__pb2.ListOrdersResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dhruva.v1.OrderService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dhruva.v1.OrderService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class OrderService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PlaceOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dhruva.v1.OrderService/PlaceOrder',
            dhruva_dot_v1_dot_orders__pb2.PlaceOrderRequest.SerializeToString,
            dhruva_dot_v1_dot_orders__pb2.Order.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dhruva.v1.OrderService/CancelOrder',
            dhruva_dot_v1_dot_orders__pb2.CancelOrderRequest.SerializeToString,
            dhruva_dot_v1_dot_orders__pb2.Order.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ModifyOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dhruva.v1.OrderService/ModifyOrder',
            dhruva_dot_v1_dot_orders__pb2.ModifyOrderRequest.SerializeToString,
            dhruva_dot_v1_dot_orders__pb2.Order.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListOrders(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dhruva.v1.OrderService/ListOrders',
            dhruva_dot_v1_dot_orders__pb2.ListOrdersRequest.SerializeToString,
            dhruva_dot_v1_dot_orders__pb2.ListOrdersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
