# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from dhruva.v1 import portfolio_pb2 as dhruva_dot_v1_dot_portfolio__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in dhruva/v1/portfolio_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PortfolioServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetPositions = channel.unary_unary(
                '/dhruva.v1.PortfolioService/GetPositions',
                request_serializer=dhruva_dot_v1_dot_portfolio__pb2.GetPositionsRequest.SerializeToString,
                response_deserializer=dhruva_dot_v1_dot_portfolio__pb2.GetPositionsResponse.FromString,
                _registered_method=True)
        self.GetEquityCurve = channel.unary_unary(
                '/dhruva.v1.PortfolioService/GetEquityCurve',
                request_serializer=dhruva_dot_v1_dot_portfolio__pb2.GetEquityCurveRequest.SerializeToString,
                response_deserializer=dhruva_dot_v1_dot_portfolio__pb2.GetEquityCurveResponse.FromString,
                _registered_method=True)
        self.GetAnalytics = channel.unary_unary(
                '/dhruva.v1.PortfolioService/GetAnalytics',
                request_serializer=dhruva_dot_v1_dot_portfolio__pb2.GetAnalyticsRequest.SerializeToString,
                response_deserializer=dhruva_dot_v1_dot_portfolio__pb2.Analytics.FromString,
                _registered_method=True)


class PortfolioServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetPositions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEquityCurve(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAnalytics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PortfolioServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetPositions': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPositions,
                    request_deserializer=dhruva_dot_v1_dot_portfolio__pb2.GetPositionsRequest.FromString,
                    response_serializer=dhruva_dot_v1_dot_portfolio__pb2.GetPositionsResponse.SerializeToString,
            ),
            'GetEquityCurve': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEquityCurve,
                    request_deserializer=dhruva_dot_v1_dot_portfolio__pb2.GetEquityCurveRequest.FromString,
                    response_serializer=dhruva_dot_v1_dot_portfolio__pb2.GetEquityCurveResponse.SerializeToString,
            ),
            'GetAnalytics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAnalytics,
                    request_deserializer=dhruva_dot_v1_dot_portfolio__pb2.GetAnalyticsRequest.FromString,
                    response_serializer=dhruva_dot_v1_dot_portfolio__pb2.Analytics.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dhruva.v1.PortfolioService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dhruva.v1.PortfolioService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PortfolioService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetPositions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dhruva.v1.PortfolioService/GetPositions',
            dhruva_dot_v1_dot_portfolio__pb2.GetPositionsRequest.SerializeToString,
            dhruva_dot_v1_dot_portfolio__pb2.GetPositionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEquityCurve(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dhruva.v1.PortfolioService/GetEquityCurve',
            dhruva_dot_v1_dot_portfolio__pb2.GetEquityCurveRequest.SerializeToString,
            dhruva_dot_v1_dot_portfolio__pb2.GetEquityCurveResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAnalytics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dhruva.v1.PortfolioService/GetAnalytics',
            dhruva_dot_v1_dot_portfolio__pb2.GetAnalyticsRequest.SerializeToString,
            dhruva_dot_v1_dot_portfolio__pb2.Analytics.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
