# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: dhruva/v1/reports.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'dhruva/v1/reports.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x64hruva/v1/reports.proto\x12\tdhruva.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf0\x01\n\x06Report\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x12\n\naccount_id\x18\x03 \x01(\t\x12\x13\n\x0bstrategy_id\x18\x04 \x01(\t\x12#\n\x04type\x18\x05 \x01(\x0e\x32\x15.dhruva.v1.ReportType\x12\x0e\n\x06period\x18\x06 \x01(\t\x12\'\n\x06\x66ormat\x18\x07 \x01(\x0e\x32\x17.dhruva.v1.ReportFormat\x12\x10\n\x08\x66ile_url\x18\x08 \x01(\t\x12\x30\n\x0cgenerated_at\x18\t \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"\x9e\x01\n\x15GenerateReportRequest\x12\x12\n\naccount_id\x18\x01 \x01(\t\x12\x13\n\x0bstrategy_id\x18\x02 \x01(\t\x12#\n\x04type\x18\x03 \x01(\x0e\x32\x15.dhruva.v1.ReportType\x12\x0e\n\x06period\x18\x04 \x01(\t\x12\'\n\x06\x66ormat\x18\x05 \x01(\x0e\x32\x17.dhruva.v1.ReportFormat\"%\n\x12ListReportsRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"9\n\x13ListReportsResponse\x12\"\n\x07reports\x18\x01 \x03(\x0b\x32\x11.dhruva.v1.Report*\xc6\x01\n\nReportType\x12\x1b\n\x17REPORT_TYPE_UNSPECIFIED\x10\x00\x12\x18\n\x14STRATEGY_PERFORMANCE\x10\x01\x12\x15\n\x11PORTFOLIO_MONTHLY\x10\x02\x12\x17\n\x13PORTFOLIO_QUARTERLY\x10\x03\x12\x14\n\x10PORTFOLIO_ANNUAL\x10\x04\x12\x08\n\x04RISK\x10\x05\x12\x0b\n\x07TAX_PNL\x10\x06\x12\x11\n\rTRADE_JOURNAL\x10\x07\x12\x11\n\rMULTI_ACCOUNT\x10\x08*J\n\x0cReportFormat\x12\x1d\n\x19REPORT_FORMAT_UNSPECIFIED\x10\x00\x12\x07\n\x03PDF\x10\x01\x12\t\n\x05\x45XCEL\x10\x02\x12\x07\n\x03\x43SV\x10\x03\x32\x97\x01\n\rReportService\x12?\n\x08Generate\x12 .dhruva.v1.GenerateReportRequest\x1a\x11.dhruva.v1.Report\x12\x45\n\x04List\x12\x1d.dhruva.v1.ListReportsRequest\x1a\x1e.dhruva.v1.ListReportsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dhruva.v1.reports_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REPORTTYPE']._serialized_start=574
  _globals['_REPORTTYPE']._serialized_end=772
  _globals['_REPORTFORMAT']._serialized_start=774
  _globals['_REPORTFORMAT']._serialized_end=848
  _globals['_REPORT']._serialized_start=72
  _globals['_REPORT']._serialized_end=312
  _globals['_GENERATEREPORTREQUEST']._serialized_start=315
  _globals['_GENERATEREPORTREQUEST']._serialized_end=473
  _globals['_LISTREPORTSREQUEST']._serialized_start=475
  _globals['_LISTREPORTSREQUEST']._serialized_end=512
  _globals['_LISTREPORTSRESPONSE']._serialized_start=514
  _globals['_LISTREPORTSRESPONSE']._serialized_end=571
  _globals['_REPORTSERVICE']._serialized_start=851
  _globals['_REPORTSERVICE']._serialized_end=1002
# @@protoc_insertion_point(module_scope)
