# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: dhruva/v1/scanner.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'dhruva/v1/scanner.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from dhruva.v1 import common_pb2 as dhruva_dot_v1_dot_common__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x64hruva/v1/scanner.proto\x12\tdhruva.v1\x1a\x16\x64hruva/v1/common.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe6\x01\n\nScanResult\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12%\n\x08\x65xchange\x18\x02 \x01(\x0e\x32\x13.dhruva.v1.Exchange\x12#\n\x07pattern\x18\x03 \x01(\x0e\x32\x12.dhruva.v1.Pattern\x12\x13\n\x0bsetup_score\x18\x04 \x01(\x01\x12\x0e\n\x06reason\x18\x05 \x01(\t\x12\x12\n\nlast_price\x18\x06 \x01(\t\x12\x12\n\nchange_pct\x18\x07 \x01(\t\x12/\n\x0b\x64\x65tected_at\x18\x08 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"X\n\x0eRunScanRequest\x12$\n\x08patterns\x18\x01 \x03(\x0e\x32\x12.dhruva.v1.Pattern\x12\x11\n\tmin_score\x18\x02 \x01(\x01\x12\r\n\x05limit\x18\x03 \x01(\x05\"9\n\x0fRunScanResponse\x12&\n\x07results\x18\x01 \x03(\x0b\x32\x15.dhruva.v1.ScanResult*`\n\x07Pattern\x12\x17\n\x13PATTERN_UNSPECIFIED\x10\x00\x12\x0c\n\x08MOMENTUM\x10\x01\x12\x12\n\x0eMEAN_REVERSION\x10\x02\x12\x0c\n\x08\x42REAKOUT\x10\x03\x12\x0c\n\x08REVERSAL\x10\x04\x32N\n\x0eScannerService\x12<\n\x03Run\x12\x19.dhruva.v1.RunScanRequest\x1a\x1a.dhruva.v1.RunScanResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dhruva.v1.scanner_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PATTERN']._serialized_start=477
  _globals['_PATTERN']._serialized_end=573
  _globals['_SCANRESULT']._serialized_start=96
  _globals['_SCANRESULT']._serialized_end=326
  _globals['_RUNSCANREQUEST']._serialized_start=328
  _globals['_RUNSCANREQUEST']._serialized_end=416
  _globals['_RUNSCANRESPONSE']._serialized_start=418
  _globals['_RUNSCANRESPONSE']._serialized_end=475
  _globals['_SCANNERSERVICE']._serialized_start=575
  _globals['_SCANNERSERVICE']._serialized_end=653
# @@protoc_insertion_point(module_scope)
